feat: add prometheus-api lib, relation (#687)
* feat: add prometheus-api lib, relation

The Prometheus charm does not provide a way for other charms to consume its prometheus api for querying metrics, apart from the opinionated grafana-source relation.  This PR implements a non-opinionated way to do this using mimir's prometheus-api interface.

* fix: unpin Relation ids in test_server_scheme.py

Previously, relations were created with specific ids.  These IDs seem to be shared across the entire pytest session, because when more relations were added in separate test files it caused:

scenario.errors.InconsistentScenarioError: Inconsistent scenario. The following errors were found: duplicate relation ID: 10 is claimed by multiple Relation instances

To fix this, explicit id's are removed from the tests in test_server_scheme.py, letting scenario generate those automatically